language: node_js
sudo: required
node_js:
  - "8"
  - "10"
  - "12"
  - "14"
env:
  - NODE_ENV=travis
services:
  - mongodb
before_install:
  - gem update --system
  - gem install sass --version "=3.3.7"
  - npm i nsp -g
after_script:
  - nsp audit-package
notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
